### ISSUE TITLE
Unknown LLVM release: clang+llvm-9.0.0-x86_64-apple-darwin.tar.xz

### ISSUE THREAD

**Issue by hellocodeM** [google/schedviz#10]
## Background
- OS: Darwin Kernel Version 19.0.0
- command: `yarn bazel run server -- -- -storage_path=traces`
- error: 
```
An error occurred during the fetch of repository 'llvm_toolchain
Unknown LLVM release: clang+llvm-9.0.0-x86_64-apple-darwin.tar.xz
Please ensure file name is correct.
```

**Comment by sabarabc** [comment]
This is an issue in one of our dependencies. Once https://github.com/grailbio/bazel-toolchain/pull/30  is merged and I bump of the version of grailbio/bazel-toolchain the build should work again on Mac OS.

As a workaround, you can downgrade to LLVM 8 by changing the version here:
https://github.com/google/schedviz/blob/7de73a91327737cfde978e86406c0cf46b3b6500/WORKSPACE#L68

**Comment by hellocodeM** [comment]
It works. Thanks!

**Comment by sabarabc** [comment]
Using LLVM 9.0.0 should work again as of f424b7ee0d70be119e9335a9c474458f4c704512

**Comment by sarsanaee** [comment]
Hi

I'm still having a similar problem with version `9.0.0`
