### ISSUE TITLE
yarn install is failing

### ISSUE THREAD

**Issue by rakyll** [google/schedviz#12]
Following the setup instructions, I cloned the repo and cd'ed into the directory:

```
$ git clone https://github.com/google/schedviz.git
$ cd schedviz
$ yarn install
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'
```

**Comment by sabarabc** [comment]
I suspect the `yarn` program you have installed is actually part of [cmdtest](https://packages.debian.org/sid/cmdtest), not the JavaScript package manager. To fix, uninstall cmdtest and install yarn following the instructions for your OS here: https://www.yarnpkg.com/en/docs/install

**Comment by rakyll** [comment]
Sorry for confirming this late but yes, it was due to the wrong yarn.
