### ISSUE TITLE
Table in Markdown in README.md isn't rendering correctly on GitHub.

### ISSUE THREAD

**Issue by mhansen** [google/schedviz#32]
This doesn't look right:

![image](https://user-images.githubusercontent.com/105529/145652956-8470a9fe-e946-4fe2-bcc0-70c69f4372eb.png)

**Comment by sabarabc** [comment]
Fixed in a9324193b07a7b3d4c95b90cf132b6134e11834e

**Comment by mhansen** [comment]
Wow, thanks for the quick fix! There are also some bullets misformatted in the last section, but those are less important, the text is still intelligible: 

![image](https://user-images.githubusercontent.com/105529/145654273-f22381b2-f427-4e79-b41c-8b9ca16eb925.png)
