### ISSUE TITLE
ubuntu 20.04: deps install needs to declare cmdtest

### ISSUE THREAD

**Issue by JonKohler** [google/schedviz#44]
Switched over from Rocky to ubuntu 20.04 

The README mentions the following for installing deps: `sudo apt-get update && sudo apt-get install build-essential unzip`

Followed by a `yarn install`; however, yarn is not installed in the apt-get above, as that requires cmdtest.

While we're on the topic of yarn install, that should also be prefixed by sudo, else you'll get:
```
jon@jk-dev-ubuntu:~/git/schedviz$ yarn install

Command 'yarn' not found, but can be installed with:

sudo apt install cmdtest
```

TLDR 
README should read: `sudo apt-get install build-esstentials unzip cmdtest`  and `sudo yarn install`

**Comment by sabarabc** [comment]
You don't want to install cmdtest (that yarn binary is something else entirely), you want to install yarn following the instructions here:
https://yarnpkg.com/getting-started/install
