### ISSUE TITLE
Server fails to find "trace.tar.gz.binproto" file

### ISSUE THREAD

**Issue by ipuustin** [google/schedviz#6]
After creating the trace (either using the `trace.sh` script or `util:trace` binary) only `trace.tar.gz` file is generated to the result directory. This leads to the following error when loading the web UI:

    Failed to get list of collections
    Reason:
     Failed to list collection metadata: open /home/ipuustin/tmp/traces/trace.tar.gz.binproto: no such file or directory

**Comment by sabarabc** [comment]
Hi,
How are you adding the trace to SchedViz? Are you copying the file into the directory given as the `storage_path` argument? If so, you need to upload the file using the "Upload File" button in the UI instead, and the storage_path folder should be empty except for the binproto files SchedViz generates.

**Comment by ipuustin** [comment]
Ah, ok, I understand now. The output directory for trace script should not be the server trace directory. Closing this issue!
